factoring commit purposed with removing isort dependency due to conflict with flake8, removing hardcoded env values for secret keeping, adding a .env.example file to show users what required variables are for the project, updating makefile commands so users can create a .env file with a single command and ensure .env file is added with cheeck-required-vars. Initial changes to use docker-compose for build process due to multiple containers needed and to use adminer tool for a u.i friendly db presentation layer. In addition github pipeline to be added to automatically run lint and formatting checks in code

diff --git a/fhir-transformer/Makefile b/fhir-transformer/Makefile
--- a/fhir-transformer/Makefile
+++ b/fhir-transformer/Makefile
@@ -1,3 +1,14 @@
+# Load environment variables
+include .env
+export $(shell sed 's/=.*//' .env)
+
+
+REQUIRED_VARS=POSTGRES_HOST \
+POSTGRES_PORT \
+POSTGRES_DB \
+POSTGRES_USER \
+POSTGRES_PASSWORD \
+
 # Variables
 PYTHON = python3
 PIP = pip3
@@ -7,25 +18,44 @@ install-requirements:
 	$(PIP) install -r requirements.txt
 
 
+# Copies .env.example & creates .env script
+init-repo:
+	cp .env.example .env
+	touch $@
+
+
+check-required-vars:
+	missing_vars=""
+	for var in $(REQUIRED_VARS); do \
+        if ! $$( printenv | grep $$var | grep -qv "PLEASE_SET_ME") && ! $$( cat .env | grep $$var | grep -qv "PLEASE_SET_ME"); then \
+            missing_vars+=" $$var"; \
+        fi; \
+    done; \
+    if [ -n "$$missing_vars" ]; then \
+        echo "Missing environment variables:$$missing_vars"; \
+        exit 1; \
+    fi	
+
+
 format: install-requirements
 	isort $(CODE_DIRS)
 	black $(CODE_DIRS)
 
 lint: install-requirements
 	flake8 $(CODE_DIRS)
-	isort --check-only $(CODE_DIRS)
 	black --check $(CODE_DIRS)
 
-python-run:
-	py ./src/utils.py
 
-docker-build:
+docker-build: check-required-vars
 	docker build -t fhir-transformer .
 
-docker-run:
-	docker run -v /fhir-transformer/data fhir-transformer
-
-docker-run-postgres:
-	docker run --name postgres -e POSTGRES_PASSWORD=fhir_password -d -p 5432:5432 postgres
+docker-run: check-required-vars
+	docker rm -f $(POSTGRES_HOST)
+	docker run --name postgres -e POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) -d -p 5432:5432 postgres
 	docker build -t fhir-transformer . 
-	docker run --rm --link postgres -e POSTGRES_PASSWORD=fhir_password fhir-transformer 
+	docker run --rm --link postgres -e POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) fhir-transformer 
+
+build-and-run: check-required-vars
+	docker-compose down
+	docker-compose build
+	docker-compose up -d
